font_family      Hack Nerd Font Mono
hide_window_decorations yes
font_size 19.0
initial_window_width  145
initial_window_height 46
shell /opt/homebrew/bin/fish
include current-theme.conf
window_margin_width 0
window_padding_width 0
single_window_margin_width 0
# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
